-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.corporations
(
    corporation_id integer NOT NULL,
    corporation_name character varying(250) NOT NULL,
    website character varying(250) NOT NULL,
    phone_number character varying(20) NOT NULL,
    PRIMARY KEY (corporation_id)
);

CREATE TABLE public.corporations_verification
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    verification boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    employee_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.jobpositions
(
    id integer NOT NULL,
    jobposition_name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobseekers
(
    jobseeker_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    nationality_id character varying(50) NOT NULL,
    date_of_birth date NOT NULL,
    PRIMARY KEY (jobseeker_id)
);

CREATE TABLE public.mail_verification
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    verification_code character varying(50) NOT NULL,
    verification boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(150) NOT NULL,
    password character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.corporations
    ADD FOREIGN KEY (corporation_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.corporations_verification
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY (jobseeker_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.mail_verification
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;